fix #108. Add improved About page.
audio-engineer/chess-teacher-front-end pull request #120
Opened 2024-04-18 15:06 UTC by SebastianMygind

This pull requests adds an improved About page that revolves around "AboutCards" which include a picture and some self chosen information about all of us, i have already created myself as an example. To add the missing information send me a message about what should be added or suggest changes through github.
sry for possible spelling mistakes in your names.

2024-04-18 19:19 UTC, audio-engineer requested changes

2024-04-18 19:19 UTC, audio-engineer commented on components/about-card.tsx
> +import { CardActionArea } from "@mui/material";
```suggestion
import CardActionArea from "@mui/material/CardActionArea";
```

2024-04-18 19:19 UTC, audio-engineer commented on components/about-card.tsx
> +import * as React from "react";
This does what?

2024-04-18 19:19 UTC, audio-engineer commented on components/about-card.tsx
> +      <Card sx={{ width: CARD_WIDTH, boxShadow: 1 }}>
Ah, so developers have to scroll up to see the width. So convenient...

2024-04-18 19:19 UTC, audio-engineer commented on components/about-card.tsx
> +            height={CARD_LENGTH}
and here

2024-04-18 19:19 UTC, audio-engineer commented on components/about-card.tsx
> +            alt={ALT_TEXT}
and here

2024-04-18 19:19 UTC, audio-engineer commented on components/about-card.tsx
> +const CARD_LENGTH = 200;
Bad variable case. In fact, completely unnecessary variables

2024-04-18 19:19 UTC, audio-engineer commented on components/about-card.tsx
> +  readonly image_name: string;
Bad case

2024-04-18 19:19 UTC, audio-engineer commented on components/about-card.tsx
> +interface AboutUsProps {
Bad naming

2024-04-18 19:19 UTC, audio-engineer commented on components/about-page.tsx
> +          description="“Sebastian Mygind, a 21-year-old computer
You didn't listen up during the meeting on the 12th of April

2024-04-18 19:19 UTC, audio-engineer commented on components/about-card.tsx
> +  readonly description: string;
See comment for usage

2024-04-18 19:19 UTC, audio-engineer commented on components/about-card.tsx
> +  const image = `/images/${image_name}`;
Bad naming and case. What's the difference between the two variables?

2024-04-22 11:13 UTC, audio-engineer approved these changes

2024-04-22 14:43 UTC, Danar435 approved these changes

2024-04-22 14:50 UTC, merged